### ISSUE TITLE
Since this package doesn't seen to be updated, I've made an updated fork

### ISSUE THREAD

**Issue by rbcorrea** [abbasfreestyle/react-native-af-video-player#135]
When creating an issue, please ensure that you provide as much information as you can. Issues with a basic description will sadly be ignored as it doesn't help diagnose the issue :(

If you don't help me, I can't help you ```¯\_(ツ)_/¯```

Here are some common things to include that can help your issue be diagnosed.

- [x] react-native-af-video-player version: lastest
- [x] React Native version: 0.59.10
- [x] OS:  Linux

- [ ] Has this issue already been raised?
Yes. And PR's that don't has been merged helped solving some issues.
- [ ] Have you clearly read and understood the Readme?
Yes
- [ ] Code and explanation to replicate this issue:
No code needed
- [ ] Are there any console logs?
Nope
- [ ] Include Screeshots / Video:

People asked to update dependencies, hoping of get rid of some bugs and some tried to contribute with PR's that didn't have enough attention.
Due to these reasons above, I've forked and changed some things, added some PRs and added to package and release it in NPM:

This package is focused on RN 0.58 ~ 0.59.

https://www.npmjs.com/package/react-native-rb-video-player

All contribution is welcome, the issue template is the same and I'll try to solve the bugs as soon as they are discovered.

**Comment by imron02** [comment]
Just like you @rbcorrea. I already pull request to your repo. But you didn't check it.

**Comment by rbcorrea** [comment]
Sorry @imron02 , I've accepted your pull request! Gonna release a new version this weekend.

Thanks!
