### ISSUE TITLE
How to style video element to overlap status bar not in fullScreen

### ISSUE THREAD

**Issue by assafb81** [abbasfreestyle/react-native-af-video-player#14]
Hi,
How can I make my video component overlap the status bar,
I want the status bar will be on-top/overlap the top row of my video

Thanks

**Comment by abbasfreestyle** [comment]
@assafb81 I'm not quite sure i understand your issue. Could you explain further with images and code please?

**Comment by assafb81** [comment]
I am trying to make the video element overlap the status bar of the device when its inline...I want the video element to start at the top of the device screen and not below the status bar
