### ISSUE TITLE
Open Youtube video from URL

### ISSUE THREAD

**Issue by shiroze** [abbasfreestyle/react-native-af-video-player#16]
Old : How to solve this problem
BVLinearGradient does not exist

Revision : Can this plugin open Youtube Video from Youtube URL ?

**Comment by abbasfreestyle** [comment]
Please take a look here. This is related to react-native-linear-gradient.

https://github.com/react-native-community/react-native-linear-gradient/issues/157

**Comment by abbasfreestyle** [comment]
Youtube support is discussed in issue #4. Closing.
