### ISSUE TITLE
Getting error on android, works fine on ios

### ISSUE THREAD

**Issue by sniib** [abbasfreestyle/react-native-af-video-player#2]
I get this error when trying to play video on android:

![nayttokuva 2017-11-26 kello 0 04 17](https://user-images.githubusercontent.com/33811558/33235274-7a3a4486-d23d-11e7-871a-85349e74f87f.png)

On ios it works smoothly. Here's the render function:

`
    render() {
        return (
                <VideoPlayer
                    url={"https://vjs.zencdn.net/v/oceans.mp4"}
                    title={"video"}
                    placeholder={"https://vjs.zencdn.net/v/oceans.png"}
                />
        )
    }
`

**Comment by abbasfreestyle** [comment]
Hi @sniib,

It sounds like a connection issue. I'm guessing your testing this on an android simulator? Check that the simulator wifi is on and can connect to the internet. Have you tried testing this on a real android device?

**Comment by sniib** [comment]
Hi @abbasfreestyle 
Thanks for fast response.
Correct, I'm using android simulator. I tested the connection and it was fine. I tried to click the play button a couple of times and the video started playing but looked like this: 

![nayttokuva 2017-11-26 kello 13 11 45](https://user-images.githubusercontent.com/33811558/33239495-8d471d60-d2ab-11e7-881b-ba1e88c6aa4a.png)

After all this I tried it on real android device and it worked fine so I guess its all good :P
Thanks a lot.

**Comment by abbasfreestyle** [comment]
@sniib,

Great, i thought that would be the case. Try using genymotion if you haven't already, i find that a better android simulator.

**Comment by PanRada** [comment]
Hi pls reopen this issue. 
Happend for me similar error on real devices - Samsung S7
Can be possibility to have this issue for use extra token on finish url ?

like this: 

render() { return ( 
<VideoPlayer url={"https://vjs.zencdn.net/v/oceans.mp4?${azure_token}"} 
}

**Comment by abbasfreestyle** [comment]
Looks like you need to use back ticks (``) if you want to use ${}

E.g.
{`https://vjs.zencdn.net/v/oceans.mp4?${azure_token}`}

**Comment by PanRada** [comment]
sorry was not clear with code example
I'm used back tick still not working

**Comment by thejasreem** [comment]
Hi, can you share the code which is working fine on iOS.

**Comment by thejasreem** [comment]
react-native version is 0.51.0

**Comment by amismailz** [comment]
I am facing this issue in ios simulator!
