### ISSUE TITLE
How to load video from local storage

### ISSUE THREAD

**Issue by rasselll** [abbasfreestyle/react-native-af-video-player#20]
Hi when i try to load from local storage i get a blank video player 

<Video source={require('../video/video.mp4')}

**Comment by WoodyPhil** [comment]
Same here. Any news about that?

**Comment by abbasfreestyle** [comment]
I'll see if I can include this in the next release. I think this should be possible.

**Comment by WoodyPhil** [comment]
This would be awesome. Thanks for the fast reply

**Comment by abbasfreestyle** [comment]
I've added local video support in version 0.1.8 :)

**Comment by WoodyPhil** [comment]
Aweseome, thanks!
But how can i use it? 
If i use the url prop it does not work :( 

![image](https://user-images.githubusercontent.com/7937191/38238161-531fb880-3729-11e8-876e-f5352ad778d0.png)

**Comment by abbasfreestyle** [comment]
You need to import your video

import myVideo from './path/to/video'

**Comment by WoodyPhil** [comment]
It's working. Thanks a lot.

**Comment by mblenton** [comment]
This works for me:
            `<Video
              url={{uri: `file:///storage/emulated/0/DCIM/video.mp4`}}
            />`
