### ISSUE TITLE
Full screen mode not covering the navbar

### ISSUE THREAD

**Issue by rasselll** [abbasfreestyle/react-native-af-video-player#21]
Hi, when I click on full screen, it does not cover the navbar

return(
  <SideMenuDrawer ref={(ref) => this._sideMenuDrawer = ref}>
  <Container style={{backgroundColor: '#fdfdfd'}}>
  <Navbar left={left} right={right} title={this.props.title} />
  <Video url={'https://your-url.com/video.mp4'}
  style={{ width: Dimensions.get('window').width, height: 200}}/>
  </Container>
  </SideMenuDrawer>
  );

**Comment by abbasfreestyle** [comment]
Hi @rasselll,

I see you're using SideMenuDrawer. What are you using for navigation and toolbar?
Also does this relate to the Readme where it explains about React Navigation fullscreen mode?

**Comment by rasselll** [comment]
Hey here is the full code for that section, would i need to somehow hide the navbar wihin onFullScreen? if so how would i do that. thanks

    onFullScreen(fullScreen) {

    }


    return(
      <SideMenuDrawer ref={(ref) => this._sideMenuDrawer = ref}>
      <Container style={{backgroundColor: '#fdfdfd'}}>
      <Video url={'http://techslides.com/demos/sample-videos/small.mp4'}
      onFullScreen={status => this.onFullScreen(status)}
      style={{ width: Dimensions.get('window').width, height: 200}}/>
      </Container>
      </SideMenuDrawer>
      );

  }

**Comment by abbasfreestyle** [comment]
> What are you using for navigation and toolbar?
> Also does this relate to the Readme where it explains about React Navigation fullscreen mode?

Could you respond to these questions please?

**Comment by rasselll** [comment]
sorry im not sure what you mean by what im using, but here is the code for the navbar. by hiding the navbar toolbar will also be hidden. 

navbar.js - file here is the code for the navbar

    export default class Navbar extends Component {
      render() {
        return(
          <Header
            style={{backgroundColor: Colors.navbarBackgroundColor}}
            backgroundColor={Colors.navbarBackgroundColor}
            androidStatusBarColor={Colors.statusBarColor}
            noShadow={true}
            >
            {this.props.left ? this.props.left : <Left style={{flex: 1}} />}
            <Body style={styles.body}>
              <Title style={styles.title}>{this.props.title}</Title>
            </Body>
            {this.props.right ? this.props.right : <Right style={{flex: 1}} />}
          </Header>
        );
      }
    }


Here is the file where I am using the navbar

    import Navbar from '../component/Navbar';

    onFullScreen(fullScreen) {
    
    }
    
    
    return(
      <SideMenuDrawer ref={(ref) => this._sideMenuDrawer = ref}>
     <Navbar left={left} right={right} title={this.props.title} />
      <Container style={{backgroundColor: '#fdfdfd'}}>
      <Video url={'http://techslides.com/demos/sample-videos/small.mp4'}
      onFullScreen={status => this.onFullScreen(status)}
      style={{ width: Dimensions.get('window').width, height: 200}}/>
      </Container>
      </SideMenuDrawer>
      );
    }

**Comment by abbasfreestyle** [comment]
You'd just need to hide the navbar on fullscreen. You can follow a similar example from the readme about react navigation fullscreen :)

{!fullscreen && <Navbar />}

**Comment by rasselll** [comment]
still doesnt work. 

export default class YourComponent extends Component {
  constructor(props) {
    super(props);

    this.state = {
      isFullScreen: false
    };
  }

  onFullScreen = fullScreen => {
    this.setState({
      isFullScreen: fullScreen
    });
  }

  render() {
    const {isFullScreen} = this.state;

    return (
      <SideMenuDrawer ref={(ref) => this._sideMenuDrawer = ref}>
        {!isFullScreen && <Navbar left={left} right={right} title={this.props.title} />}

        <Container style={{ backgroundColor: '#fdfdfd' }}>
          <Video
            url={'http://techslides.com/demos/sample-videos/small.mp4'}
            onFullScreen={this.onFullScreen}
            style={{ width: Dimensions.get('window').width, height: 200 }} />
        </Container>
      </SideMenuDrawer>
    );
  }
}
