### ISSUE TITLE
error playing this video (on every video)

### ISSUE THREAD

**Issue by WoodyPhil** [abbasfreestyle/react-native-af-video-player#25]
When creating an issue, please ensure that you provide as much information as you can. Issues with a basic description will sadly be ignored as it doesn't help diagnose the issue :(

If you don't help me, I can't help you ```¯\_(ツ)_/¯```

Here are some common things to include that can help your issue be diagnosed.

- [x] react-native-af-video-player version: 0.1.7
- [X] React Native version: 0.50 
- [X] OS: OS-X

- [X] Has this issue already been raised? No

- [X] Have you clearly read and understood the Readme? Yes

- [X] Are there any console logs? No
- [X] Code and explanation to replicate this issue: Just the default example code, but no video is working.

- [X] Include Screeshots / Video: ![image](https://user-images.githubusercontent.com/7937191/38092399-6d82117e-3368-11e8-81e0-f4aa017098bf.png)
![image](https://user-images.githubusercontent.com/7937191/38092516-bd92460c-3368-11e8-8069-b3edeab8d30a.png)

**Comment by abbasfreestyle** [comment]
Hi @WoodyPhil,

This doesn't work because you're using a youtube url.
Closing because this relates to issue #3 

Thank you for using the checklist :)

**Comment by zootopia106** [comment]
I am also faced with this error but for now i didn't even use youtube url.
@abbasfreestyle , Did you solve this problem?
