### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by weizhiyang** [abbasfreestyle/react-native-af-video-player#27]
when I finish the video page in my APP,I found the other pages can also rotate ,I think you should remove the orientation listener when the conponent unmount in the video page so that it will not influence on the other pages

**Comment by abbasfreestyle** [comment]
Thanks for the suggestion @weizhiyang,

Have you tried adding `lockPortraitOnFsExit`, does that stop your app pages from rotating?

**Comment by weizhiyang** [comment]
Thank you very much!The problem has been solved with your help.
