### ISSUE TITLE
What video format does this support?

### ISSUE THREAD

**Issue by stepanpetrov** [abbasfreestyle/react-native-af-video-player#29]
Hello, there.
I am very fine to find this.
But I have one question about using this.
Please let me know what video format this support.
Thank you a lot.

**Comment by abbasfreestyle** [comment]
Hello @stepanpetrov,

This module uses react-native-video. Here's a link about supported formats for android:
https://github.com/react-native-community/react-native-video/tree/master/android-exoplayer

I'm not sure which formats support iOS, however i imagine it would be similar.

**Comment by stepanpetrov** [comment]
Thank you.
