### ISSUE TITLE
works with youtube / vimeo url?

### ISSUE THREAD

**Issue by cinder92** [abbasfreestyle/react-native-af-video-player#3]
it works?

**Comment by abbasfreestyle** [comment]
This component extends off react-native-video so it wouldn't support YouTube unfortunately.

If you need YouTube videos, take look at https://github.com/inProgress-team/react-native-youtube
This is a really good component.

Vimeo sadly offers no support to its customers for app video players. The only way to get vimeo videos to play is by having a paid business account and retrieve the raw urls there.

**Comment by MSSPL-PiyaleeMaiti** [comment]
@abbasfreestyle I use this plugin for my project. I have two type of video 1. youtube and another one our uploaded video on our server. Now I don't want to use two plugins for video play, can't I play youtube video using this plugin? It'll be very helpful if both types of video will play using one react native package.

**Comment by ashokkumar88** [comment]
please add youtube support.
