### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by assafb81** [abbasfreestyle/react-native-af-video-player#38]
placeholder issues:
I am passing an image to the package to "play" as a placeholder but:
In IOS device it is placed under the video component and no inside.
in Android it does not visible at all.

I want that the first image of a video will be the placeholder, the videos are stored on the cloud.
I tried to save the first image locally for that.
Or the package takes the 1st image of the video automatically?

OR why not use `poster` of `react-native-video`

**SOLVED**
I just updated `image` style in `Video.js`:
```
image: {
        ...StyleSheet.absoluteFillObject,
        width: '100%', // <- added
        height: '100%', // <- added
        zIndex: 99,
},
```

Great package!!

**Comment by padampadam** [comment]
my images are also not filling the video container. adding width and height fixes that
