### ISSUE TITLE
View Config not found for name BVLinearGradient

### ISSUE THREAD

**Issue by chanthea** [abbasfreestyle/react-native-af-video-player#39]
First try and this happened. I just copy paste your sample code.

"react": "16.3.1",
 "react-native": "0.55.3",
"react-native-af-video-player": "^0.1.9",
OS : window 10. Test on Emulator Nexus 5 Api 23 

![capture2](https://user-images.githubusercontent.com/13411778/39410445-88e0fc14-4c22-11e8-9339-f5534829ad2e.PNG)

![capture](https://user-images.githubusercontent.com/13411778/39410406-e40f2da0-4c21-11e8-91f2-631a45a72d49.PNG)

**Comment by pheromone** [comment]
@chanthea I made this mistake here too. What should I do?

**Comment by d41z** [comment]
@chanthea could u solve it?

**Comment by pheromone** [comment]
@d41z 
我这边解决好了.我 react-ntive link,fix it.
I'm done here. I react-ntive link,ok.

**Comment by Sabai369** [comment]
+1

**Comment by hungnv1709** [comment]
react-native link:  it doesn't work for me. do u have another way to fix it.

**Comment by chanthea** [comment]
Not work if you are using expo. Well i able to make this work by install all packages that mention you to link in read me. 
Note : don't ever use react-native link randomly. It will link all available native packages in your project.

**Comment by nicoara** [comment]
this issue should still be open, no linking works. not using expo.

**Comment by chawkibenalaya** [comment]
Try to rebuild , no need to link for RN > 0.60 on android 
on ios just make npx pod install
