### ISSUE TITLE
do not show fullscreen within scrollview

### ISSUE THREAD

**Issue by B4UGUYS** [abbasfreestyle/react-native-af-video-player#5]
Hello admin, how can I show fullscreen if the videoplayer component is within scrollview ?
I know u have pointed this issue, but how can I show fullscreen?
Thanks for your awesome video player.

**Comment by B4UGUYS** [comment]
I solve this issue by adding zIndex: 99 within fullscreen style

  fullScreen: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 99
  }

**Comment by abbasfreestyle** [comment]
I'll have a try myself to see if that fixes it. I have a feeling i tried this before and it fills the entire scrollview, meaning fullscreen mode is also scrollable.

I hope I'm wrong because I'd like to include this feature too! Will keep you updated :)

**Comment by B4UGUYS** [comment]
Thanks for your reply

**Comment by abbasfreestyle** [comment]
Sadly this doesn't work. Am I guessing you applied this fix in VideoPlayer.js right?
If so, I'm still seeing the same effect that fullscreen mode is scrollable.

If anybody else have a solution feel free to comment here.

**Comment by abbasfreestyle** [comment]
@B4UGUYS I've added a workaround for fullscreen support inside a ScrollView with version 0.1.5

Take a look at the readme again for examples. It should now work. 👍

**Comment by B4UGUYS** [comment]
Thanks dude !
