### ISSUE TITLE
Invariant violation:View config not found for name BVLinerGradient

### ISSUE THREAD

**Issue by pheromone** [abbasfreestyle/react-native-af-video-player#54]
![image](https://user-images.githubusercontent.com/14305431/40834404-4c4eac0a-65c3-11e8-8648-3f948ec27616.png)

can not use!!!
Invariant violation:View config not found for name BVLinerGradient

- [ ] react-native-af-video-player version:  ^0.2.1
- [ ] React Native version:0.55.4
- [ ] OS: iOS && Android

**Comment by pheromone** [comment]
@yogeshmoradiya121  i use ` react-native link ` fix it.

**Comment by kaixiniOSTT** [comment]
我用的pod , link了还是报这个错误
