### ISSUE TITLE
FullScreen doesn't work when the  inside A modal !!

### ISSUE THREAD

**Issue by yjose** [abbasfreestyle/react-native-af-video-player#58]
Hi thank you for this great work 

I just used the Video component inside A react modal, it works perfectly but when I press the fullscreen button, the app stooped and not responded.
Any help here !!!!  
 
- [ ] react-native-af-video-player version: 0.2.1
- [ ] React Native version: 0.55.4
- [ ] OS:  IOS

**Comment by padampadam** [comment]
you need to set supportedOrientations
<Modal
        visible={true}
        supportedOrientations={['portrait', 'landscape']}
      >
