### ISSUE TITLE
无法在视频上面放置其他按钮吗?如,返回按钮.

### ISSUE THREAD

**Issue by pheromone** [abbasfreestyle/react-native-af-video-player#59]
无法在视频上面放置其他按钮吗?如,返回按钮.
Can't put any other buttons on video? For example, return button.
react-native: 0.55.4
react-native-af-video-player: ^0.2.1
OS:iOS & Android

![image](https://user-images.githubusercontent.com/14305431/41333140-4136022e-6f13-11e8-8f9f-bfcba68e175d.png)

**Comment by pheromone** [comment]
OS:android
iOS is ok,but android is not ok.
```
{/*视频*/}
                <View>
                <Video
                    style={{width:width,height:200,overflow:'hidden'}}
                    url={videoInfo.video}
                    placeholder={videoInfo.titleImages[0]}
                    onProgress = {(info)=>this.onProgress(info)}
                />
                </View>
                <Image style={{width:22,height:22,position:'absolute',top:20,left:15}} source={Images.General.back_btn}/>
```
![Uploading image.png…]()

**Comment by pheromone** [comment]
![image](https://user-images.githubusercontent.com/14305431/41335018-056f8574-6f1a-11e8-9f58-a461553a8ded.png)

**Comment by cleoTang** [comment]
Hello, have you solved it? I have this problem now.

**Comment by pheromone** [comment]
@cleoTang  i use native code fix it. i dont know too use react native  fix it
