### ISSUE TITLE
Infinity Progress - was (Unrecognized selector)

### ISSUE THREAD

**Issue by guilharj** [abbasfreestyle/react-native-af-video-player#6]
Hi Guys, nice lib. But I'm was testing and android worked fine, but IOS I get this error when click over the video (play or pause) . iOS 11.2. 

After closing the red screen appears to work fine. ( in debug mode) 

 "react-native": "0.47.1",
 "react-native-af-video-player": "^0.1.3",
"react-native-video": "2.0.0"

Have you faced this problem?  Check the image with the original message. 

![image](https://user-images.githubusercontent.com/13605710/34995251-0b566c22-fabd-11e7-8066-f2ee30974e99.png)

**Comment by guilharj** [comment]
I think that I've figured out  how where is the problem.  And appears to be the react-native-slider library.  After a deep deep deep debuging of the UIManager.

the Slider.js file has a definition like this:
`
<Animated.View
          onLayout={this._measureThumb}
          renderToHardwareTextureAndroid={true}
          style={[
            {backgroundColor: thumbTintColor},
            mainStyles.thumb, thumbStyle,
            {
              transform: [
                { translateX: thumbLeft },
                { translateY: 0 }
              ],
              ...valueVisibleStyle
            }
          ]}
        >
          {this._renderThumbImage()}
        </Animated.View>
`

The problem is in the transform style.  The Xcode debug console said "Error setting property 'transform' of RCTView with tag #360: Exception thrown while executing UI block: -[NSNull floatValue]: unrecognized selector sent to instance 0x107793ef0"

if I remove this transformation, the code works fine.  If anyone with more knowledge of this lib knows the reason, will help a lot. I will still work on this.

**Comment by guilharj** [comment]
UPDATE.  I think that the slider needs parameters like minimum and maximum value to the slider. BUT, I'm using a live streaming and this could be tricky. 

  var thumbLeft = value.interpolate({
      inputRange: [minimumValue, maximumValue],
      outputRange: [0, containerSize.width - thumbSize.width],
      //extrapolate: 'clamp',
    });

A Idea to solve this, is deal with live streams at the  video control in a different way of common video.  What about not using the slider on live streams?

**Comment by guilharj** [comment]
So, bc the livestream, the progress ins Infinity. So what about this idea?

<View style={styles.container}>
      { Platform.OS === 'ios' ?
        <Slider
          onValueChange={val => props.onSeek(val)}
          onSlidingComplete={val => props.onSeekRelease(val)}
          value={**progress === Number.POSITIVE_INFINITY ? 0: progress**}
          thumbTintColor={theme}
          thumbStyle={thumbStyle}
          trackStyle={trackStyle}
          minimumTrackTintColor={theme}
          maximumTrackTintColor={trackColor}
        />

**Comment by guilharj** [comment]
@abbasfreestyle  What you think?

**Comment by guilharj** [comment]
https://github.com/guilharj/react-native-af-video-player/commit/e0ed9b860dcb0403f817b484228245d772508fa8

Feel free to merge.  BYe BYe

**Comment by abbasfreestyle** [comment]
Hi @guilharj,

Thanks for the PR. I agree. I think that's the best approach for now. I haven't really tested this with live streaming, so if it's all working as expected that's awesome :)

I'll close this as soon as it's merged.

**Comment by guilharj** [comment]
Another Way, is not showing the slider, and show a label like "Live Broardcast" The Macos player used on safari do something like this :)

**Comment by abbasfreestyle** [comment]
Sounds like a good idea. I may consider this for the future. For now the original solution is good enough :)

**Comment by abbasfreestyle** [comment]
@guilharj Added your fix in 0.1.4 👍

**Comment by GazizovRuslan** [comment]
I get this problem, i dont use slider, anybody have any ideas?
![simulator screen shot - iphone x - 2018-05-16 at 17 05 32](https://user-images.githubusercontent.com/15098966/40113656-0070e382-592c-11e8-8fc1-347fe490e174.png)

`import Video from "react-native-af-video-player";

class LiveTranslation extends Component {
  static navigationOptions = {
    title: "Live",
    headerTintColor: "#ffffff",
    headerStyle: {
      backgroundColor: "#0e305d"
    }
  };

  render() {
    const url = 'http://mysite.kz/rtplive/mpegts.stream/playlist.m3u8';
    const placeholder = "http://mysite.kz/1.jpg";
    return (
      <View style={style.videoContainer}>
        <Video url={url} placeholder={placeholder} rotateToFullScreen/>
      </View>
    );
  }
}

export default LiveTranslation;`
