### ISSUE TITLE
Tried to register two views with the same name RCTVideo

### ISSUE THREAD

**Issue by havinhthai** [abbasfreestyle/react-native-af-video-player#61]
Here are some common things to include that can help your issue be diagnosed.

- [x] react-native-af-video-player version: 0.2.1
- [x] React Native version: 0.55.4
- [x] OS: iOS and Android

- [x] Has this issue already been raised? Yes

- [x] Have you clearly read and understood the Readme? Yes

- [x] Code and explanation to replicate this issue: 
Everytime when I tried to `import Video from 'react-native-af-video-player'` my app have errors `Unhandled JS Exception: Tried to register two views with the same name RCTVideo` and `Module AppRegistry is not a registered callable module (calling runApplication)`

- [x] Include Screeshots / Video:
![screenshot_1529565535](https://user-images.githubusercontent.com/19555791/41703622-2546ec44-755e-11e8-9800-5393b37dbcf0.png)

**Comment by shrivastavaanurag** [comment]
i am facing same issue

**Comment by yarakanigara** [comment]
still hwaiting

**Comment by sudiddo** [comment]
is there any solution for this?

**Comment by yarakanigara** [comment]
@havinhthai can you give me the code that mentioned by error logs?

**Comment by havinhthai** [comment]
@yarakanigara Is this?
```
07-03 15:46:58.816 1015-1039/com.elearning E/Surface: getSlotFromBufferLocked: unknown buffer: 0xe19d2be0
07-03 15:47:00.365 1015-1039/com.elearning E/Surface: getSlotFromBufferLocked: unknown buffer: 0xe19d2b40
07-03 15:47:01.376 1015-1079/com.elearning E/ReactNativeJS: Tried to register two views with the same name RCTVideo
07-03 15:47:01.408 1015-1079/com.elearning E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)

```

**Comment by yarakanigara** [comment]
@havinhthai I mean your line of code that produced that error message..
The most possible answer because you import 'react-native-video' twice. Since 'react-native-af-video-player' **already import** 'react-native-video' we should not import 'react-native-video' again. CMIIW

**Comment by shrivastavaanurag** [comment]
thanks issue resolved.

**Comment by hungdev** [comment]
i get same issue. i didnt import  'react-native-video' again. but it still gets error.

**Comment by tarunmehta-quovantis** [comment]
I am having the same issue when I am importing "react-native-responsive-linechart"
any solution?
@shrivastavaanurag @yarakanigara @shrivastavaanurag

**Comment by arasemami** [comment]
I am facing the same issue, I use` react-native-video` and `react-native-af-video-player` in two different components, I need both for my project, how can I use this two package together?

**Comment by arasemami** [comment]
> i get same issue. i didnt import 'react-native-video' again. but it still gets error.

did you clean your, `settings.gradle` , `android/build.gradle` , `MainApplication.java` files?

**Comment by ChandniSharma** [comment]
any one has a solution ? I am facing the same issue in 'Gifted Chat'

**Comment by ChandniSharma** [comment]
I uninstall both liabraries than intall my 'Gifted Chat' liabrary than install 'react-native-video' liabrary and now it's working.

**Comment by lostomato** [comment]
> I uninstall both liabraries than intall my 'Gifted Chat' liabrary than install 'react-native-video' liabrary and now it's working.

That's right. I think the problem is the caused by installation of more than one react-native-video.  Use "npm list | grep react-native-video" to check how many react-native-video versions in your project. Delete the useless ones.

**Comment by wahabraza404** [comment]
@arasemami Did you find any solution...?I have same issue.

**Comment by zosmak** [comment]
Faced the same problem. What worked for me was using yarn's [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/).

In package.json:
"dependencies": {
 ...
 "react-native-video": "^5.0.0",
},
"resolutions": {
 "react-native-af-video-player/react-native-video": "^5.0.0"
}

**Comment by Fay-0768** [comment]
> I am facing the same issue, I use` react-native-video` and `react-native-af-video-player` in two different components, I need both for my project, how can I use this two package together?

I have the same requirement, did you find any solution to hold both?
