### ISSUE TITLE
Autoplay Vertical Video in Fullscreen?

### ISSUE THREAD

**Issue by padampadam** [abbasfreestyle/react-native-af-video-player#7]
I can play Vertical Video and it goes to FullScreen if i press the Button, but if i set fullScreenOnly, it automatically rotates.
I want it to go FullScreen without Rotation?

**Comment by abbasfreestyle** [comment]
Hi @padampadam,

I think I potentially see where the problem could be. I'll take a deeper look this week and find out why it's doing this.

**Comment by abbasfreestyle** [comment]
@padampadam fixed in version 0.1.4 👍
