### ISSUE TITLE
Can't load videos from YouTube or any other online video platforms

### ISSUE THREAD

**Issue by ShridharCodewave** [abbasfreestyle/react-native-af-video-player#72]
const url = 'https://youtu.be/ZL4pokf2pT8'

The above url is just an example.

**Comment by vforvasile** [comment]
Hey @ShridharCodewave. This library is a wrapper for react-native-video, you can't use Youtube videos as urls because of YT API policy. Try this library instead: https://github.com/inProgress-team/react-native-youtube - you'll need an API key to use it!

**Comment by ShridharCodewave** [comment]
Thank you very much @vforvasile  for the reply and I have one more question. If i have videos stored in firestore can I use those urls to play videos? (I apologies for my bad English)

**Comment by vforvasile** [comment]
I'm not aware of how the Firebase API works. At the moment, only Vimeo and Youtube is not supported. Give it a try and let us know ;)

**Comment by ShridharCodewave** [comment]
Yeah I stored a video on firestore and used its url the app is working properly. Thanks for the help :)

**Comment by ShridharCodewave** [comment]
Is there any way to restrict the length of the video being played?

**Comment by davekedar** [comment]
@ShridharCodewave but what about the private videos? 

please check my issue
https://github.com/abbasfreestyle/react-native-af-video-player/issues/98

**Comment by ShridharCodewave** [comment]
@davekedar  I dont think you can play encoded videos.

**Comment by davekedar** [comment]
any solution which is other then this library, any way we can play that in React Native?

**Comment by ShridharCodewave** [comment]
@davekedar  can you make that encoded video url public? (In your issue #98 )

**Comment by davekedar** [comment]
but then it is being used by web too, isn't it risky?

**Comment by ShridharCodewave** [comment]
@davekedar  then I think you should try some other alternative video players and see if that works,
But sorry I haven't tried using any video players. Also if you can store videos on Vimeo you can try react-native-vimeo.
