### ISSUE TITLE
full screen rotation

### ISSUE THREAD

**Issue by keshamtravels** [abbasfreestyle/react-native-af-video-player#73]
i clicked the video to play then went to full screen , it didn't rotate on rotating the mobile(android), and then i went to small screen then came back to full screen , it did rotate then on rotating mobile and then after first time it rotated always as i wanted ,
why it didn't rotate on first time.

**Comment by vforvasile** [comment]
Can you post the code here? <Video> Component with all the props and the <View> that wraps it?

**Comment by bhoomika911** [comment]
@keshamtravels ...I have couple of questions here:

1.This orientation setting , we need to do in androidmanifest file . Right? 
2.What should be the value of "android:orientation"?
3.We need to set this for application or activity?
