### ISSUE TITLE
After the full screen, the video is played, and the play button is clicked again. The video can't be played. (Android)

### ISSUE THREAD

**Issue by mvpdream** [abbasfreestyle/react-native-af-video-player#8]
After the full screen, the video is played, and the play button is clicked again. The video can't be played. (Android)

**Comment by abbasfreestyle** [comment]
I can't seem to replicate this issue.
No code, project version data or screenshots makes it hard to diagnose your issue.

**Comment by mvpdream** [comment]
![2018-02-02-09-53-16](https://user-images.githubusercontent.com/16203724/35712851-32d9970c-07ff-11e8-9d87-fa3d0d503073.gif)
![_20180202091917](https://user-images.githubusercontent.com/16203724/35712868-4bbf0162-07ff-11e8-97b7-0a41fade9fdc.png)
The first step is to open the video in the linkage mode and suspend the function of the playback.

The second step, switch to full screen mode.

The third step, again switch to the linkage mode, video abrupt interruption, suspend play function failure.

**Comment by mvpdream** [comment]
@abbasfreestyle

**Comment by abbasfreestyle** [comment]
@mvpdream I've pushed a fixed in version 0.1.6

Thanks for raising this issue. Let me know if this has fixed it :)
