### ISSUE TITLE
Error Code -11800, AVFoundationErrorDomain

### ISSUE THREAD

**Issue by matteocollina** [abbasfreestyle/react-native-af-video-player#82]
The player has always worked with this video, from today I get this error:

![schermata 2018-09-26 alle 09 42 09](https://user-images.githubusercontent.com/8715726/46064723-79471680-c170-11e8-9ce0-11d350dadbb6.png)

This is the code:
```
<View style={{ flex: 3 }}>
    <Video
        ref={(ref) => { this.video = ref }}
        style={styles.video}
        url={require('./../../assets/videos/video_promo.mp4')}
        resizeMode='contain'
        inlineOnly={true}
        logo=' '
        onError={(error)=>{
            console.log("Error in Video",error)
        }}
        error={false}
    />
</View>
```

- [X] react-native-af-video-player version: 0.2.1
- [X] React Native version:  0.55.4
- [X] OS: macOS 10.13.3

**Comment by no-weller** [comment]
@matteocollina Are you getting this error on the Simulator? It seems that react-native-video has some problems with playing videos from local file system inside the Emulator/Simulator: https://github.com/react-native-community/react-native-video/issues/644#issuecomment-358885148

By the way, isn't the path of your resource correct? It seems, that there is either missing one more 'dot' or there are one dot and slash to much => `require('../../assets/videos/video_promo.mp4')` or `require('../../../assets/videos/video_promo.mp4')`

**Comment by matteocollina** [comment]
@no-weller I do not know why, but it was a temporary mistake. Not changing anything is back to work.
