### ISSUE TITLE
How can I pause the video. I want to control the video pausing based on a condition. 

### ISSUE THREAD

**Issue by ronastlelobo** [abbasfreestyle/react-native-af-video-player#83]
Thank you @sure1243jupiter .  I am closing the Issue !

**Comment by sure1243jupiter** [comment]
hi @ronastlelobo 
you can do by referencing the video component

declare like this
```
<Video 
ref={(ref)=>{this.video}=ref}}
......
>
```

the **Video** is the imported name from **react-native-af-video** library

**`import Video from 'react-native-af-video-player';`**

and then you can use that reference to play/pause where ever you want in the parent component like this

`this.video.paly()` to play and
`this.video.pause()` to pause video
