### ISSUE TITLE
option to lock to portrait after fullscreen

### ISSUE THREAD

**Issue by padampadam** [abbasfreestyle/react-native-af-video-player#9]
After fullscreen is disabled you are calling Orientation.unlockAllOrientations(), but my App generally is locked to Portrait, which causes it to bounce around.
Maybe you could add an lockTo option.
Anyways, thanks a lot for the project, keep it up

**Comment by abbasfreestyle** [comment]
Thanks @padampadam, I've added this in version 0.1.6
